services:
  mongo:
    image: mongo:7.0
    container_name: metrics-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
  backend:
    build:
      context: ./clinical-mortality-app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATAIKU_API_URL=${DATAIKU_API_URL}
      - DATAIKU_API_TOKEN=${DATAIKU_API_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
    volumes:
      - ./clinical-mortality-app/backend:/app
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./clinical-mortality-app/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: