services:
  backend:
    build:
      context: ./clinical-mortality-app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATAIKU_API_URL=${DATAIKU_API_URL}
      - DATAIKU_API_TOKEN=${DATAIKU_API_TOKEN}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - SENDER_PASSWORD=${SENDER_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - ./clinical-mortality-app/backend:/app
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./clinical-mortality-app/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge